services:
  - type: web
    name: numis-backend
    env: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MONGODB_URI
        value: mongodb+srv://espinozaplazarodrigo:iqLOKaV7ZAutdhFR@cluster0.gip4i.mongodb.net/numismatica
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
